API_FULLTEXT_MAPPER = {
    "remarks":"Remarks",
    "val": "Value",
    "inv_typ": "Invoice_Type",
    "pos": "Place_of_Supply",
    "idt": "Invoice_Date",
    "rchrg": "Reverse_Charge",
    "inum": "Invoice_Number",
    "f_year": "Financial_Year",
    "imonth": "Invoice_Month",
    "supplier_gstin": "Supplier_GSTIN",
    "supplier_name": "Supplier_Name",
    "supplier_gstin_status": "Supplier_GSTIN_Status",
    "supplier_return_type": "Supplier_Return_Type",
    "contact_name": "Contact_Name",
    "buyer_gstin": "Buyer_GSTIN",
    "cfs": "Counter_Filling_Status",
    "invoice_type": "Invoice_Type",
    "gstr1_filling_date": "GSTR1_Return_Filling_Date",
    "gstr3b_filling_status": "GSTR3B_Return_Filling_Status",
    "ttxval": "Total_Taxable_Value",
    "net_amount": "Net_Amount",
    "auto_reco_id": "Auto_Reconsilation_ID",
    "match_status": "Match_Status",
    "itc_elg": "ITC_Eligiblity",
    "ERP_document_number": "ERP_Document_Number",
    "ERP_document_date": "ERP_Document_Date",
    "total_igst": "Total_IGST_Amount",
    "total_cgst": "Total_CGST_Amount",
    "total_sgst": "Total_SGST_Amount",
    "total_cess": "Total_CESS_Amount",
    "transaction_number": "Transaction_Number",
    "reco_action": "Reconsilation_Action",
    "action_date": "Action_Date",
    "referred_invoice_num": "Referred_Invoice_Number",
    "referred_invoice_date": "Referred_Invoice_Date",
    "mismatch_reason": "Mismatch_Reason",
    "nt_dt" : "Note_Date",
    "nt_num" : "Note_Number",
    "gl_code" : "GL_Code",
    "ntty" : "Note_Type",
    "portcode" : "Port_Code",
    "pr_data_buyer_gstin": "Purchase_Buyer_GSTIN",
    "pr_data_supplier_gstin": "Purchase_Supplier_GSTIN",
    "pr_data_invoice_type": "Purchase_Invoice_Type",
    "pr_data_net_amount": "Purchase_Net_Amount",
    "pr_data_val": "Purchase_Value",
    "pr_data_idt": "Purchase_Invoice_Date",
    "pr_data_nt_dt": "Purchase_Note_Date",
    "pr_data_inum": "Purchase_Invoice_Number",
    "pr_data_nt_num": "Purchase_Note_Number",
    "pr_data_ntty": "Purchase_Note_Type",
    "pr_data_pos": "Purchase_Place_of_Supply",
    "pr_data_ERP_document_number": "Purchase_ERP_Document_Number",
    "pr_data_ERP_document_date": "Purchase_ERP_Document_Date",
    "pr_data_location": "Purchase_Location",
    "pr_data_portcode": "Purchase_Port_Code",
    "pr_data_total_cgst": "Purchase_Total_CGST_Amount",
    "pr_data_total_sgst": "Purchase_Total_SGST_Amount",
    "pr_data_total_cess": "Purchase_Total_CESS_Amount",
    "pr_data_total_igst": "Purchase_Total_IGST_Amount",
    "pr_data_referred_invoice_num": "Purchase_Referred_Invoice_Number",
    "pr_data_referred_invoice_date": "Purchase_Referred_Invoice_Date",
    "pr_data_rchrg": "Purchase_Reverse_Charge",
    "pr_data_org_inum": "Purchase_Original_Invoice_Number",
    "pr_data_org_idt": "Purchase_Original_Invoice_Date",
    "pr_data":"Purchase",
    "reference_invoices":"Reference_Invoices",
    "ont_num":"ont_Number",
    'ont_dt': 'ont_Date',
    "org_inum":"Organization_Invoice_number",
    "org_idt":"Organization_Invoice_Date",
    }