


#----------------------------------------------------------------
from collections.abc import Iterator
from langchain.schema.messages import BaseMessage
from langchain_core.messages import AIMessageChunk
from langchain_core.messages import HumanMessage
from llama_index.core.chat_engine import SimpleChatEngine
#from litellm import LiteLLM
from llama_index.llms.litellm import LiteLLM
from llama_index.core.llms import LLM

import asyncio
import re

from typing import Any, List, Dict, Optional,AsyncIterator
from openai import OpenAI
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
#import spacy
import re

class SimpleAnswer:
    def __init__(self, config,question: str,docs: List[Any], persona: Dict[str, str], message_history: Optional[List[BaseMessage]] = None) -> None:
        self.question = question
        self.llm = self.load_litellm_as_llm(config)
        self.message_history = message_history or []
        self.docs = docs or []
        self.persona = persona
        self.index=None

    def _build_prompt(self, content: str) -> str:
        """Builds the prompt for the LLM based on the content and question."""
        prompt = f"{self.persona['persona']}.\n Answer the following question based on the content provided and persona you are based on:\n"
        prompt += f"Content: {content}\n"
        
        
        return prompt

    def load_litellm_as_llm(self,config):
        """
        Load LiteLLM as an LLM in LlamaIndex with the provided configuration.

        Args:
            config (dict): Configuration parameters for LiteLLM, such as model_name, temperature, etc.

        Returns:
            LLM: An instance of LiteLLM configured for use in LlamaIndex.
        """
        # Extract configuration parameters
        model_name = config.get('model_name', 'default_model')
        temperature = config.get('temperature', 0.7)
        max_tokens = config.get('max_tokens', 150)

        # Initialize LiteLLM with the specified configuration
        litellm_instance = LiteLLM(model_name=model_name, temperature=temperature, max_tokens=max_tokens)

        # Create an LLM instance for LlamaIndex
        llm_instance = litellm_instance

        return llm_instance

    
    async def response(self, prompt: str, query: str) -> str:
        """Fetch response from chat engine."""
        #self.index=self.llm_config(config=None)
        #llm_index=self.index
        chat_engine = SimpleChatEngine.from_defaults(llm=self.llm,system_prompt=prompt)
        response = chat_engine.chat(query)
        return response

    async def fetch_response(self, prompt: str) -> str:
        """Fetch response from OpenAI based on the constructed prompt."""
        client = OpenAI()  # Ensure you have your OpenAI API client set up
        response_content = ""

        # Create a completion request
        response = await client.chat.completions.create(
            model=self.llm,
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": prompt}
            ],
        )
        
        message = response.choices[0].message
        response_content = message.content
        return response_content

    async def _raw_output(self) -> AsyncIterator[str]:
        """Generates output from the LLM based on the constructed prompts for each content."""
        if self.docs:
            limited_docs = self.docs
            for index, item in enumerate(limited_docs):
                content = clean_content(item.content)  # Clean content asynchronously
                prompt = self._build_prompt(content)
                response = await self.response(prompt=prompt, query=self.question)

                # Create citation in the desired format
                
                yield response

    
    @property
    async def llm_answer(self) -> AsyncIterator[str]:
        """Compiles the final answer from processed output."""
        
        combined_answer=""
        # yield final_output
        async for response in self._raw_output():
            combined_answer+=(f"{str(response)}\n")
        
        final_output,citations=self.citations(combined_answer)
        answer={
            "response":final_output,
            "citations":citations
        }
        yield answer


    def citations(self,response):
        """
        Generates an annotated response with citations based on document content.

        Args:
            response (str): The initial response generated by the LLM.

        Returns:
            tuple: A tuple containing the updated response with citations and a dictionary of citations.
        """
        # Step 1: Prepare documents for vectorization
        documents = [doc.content for doc in self.docs]  # Assuming docs is a list of dicts
        vectorizer = TfidfVectorizer()
        vectors = vectorizer.fit_transform(documents).toarray()

        # Step 2: Split response into sentences
        response_sentences = response.split('. ')  # Simple split; consider using NLP for better sentence tokenization

        citations = {}
        annotated_response = []

        for sentence in response_sentences:
            # Vectorize each sentence
            sentence_vector = vectorizer.transform([sentence]).toarray()
            
            # Calculate cosine similarity to each document vector
            similarity_scores = cosine_similarity(sentence_vector, vectors)
            
            # Find the best matching document index
            best_match_index = similarity_scores.argmax()
            
            # Create citation entry
            citation_index = len(citations) + 1
            citations[str(citation_index)] = self.docs[best_match_index].document_id  # Use 'id' from your document structure
            
            # Append annotated sentence with citation
            annotated_response.append(f"{sentence.strip()} [{citation_index}]")

        # Combine annotated sentences into a final response
        final_response = ' '.join(annotated_response)
        
        return final_response, citations


    def add_to_history(self, response: str) -> None:
        """Adds a response to the message history."""
        self.message_history.append(HumanMessage(content=response))

def clean_content(content: str) -> str:
    """Cleans the input content."""
    cleaned = content.strip()
    cleaned = re.sub(r'\s+', ' ', cleaned)
    cleaned = cleaned.replace('{', '').replace('}', '')
    return cleaned

